# Generated by Django 4.2.3 on 2023-07-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('JR', 'Junior Developer'), ('MD', 'Middle Developer'), ('SR', 'Senior Developer')], default='JR', max_length=2)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job_image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Contact',
                'ordering': ['-published_at'],
            },
        ),
    ]
