# Generated by Django 4.2.3 on 2023-07-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='job_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
