# Generated by Django 4.2.3 on 2023-07-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_contact_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='job_image',
            new_name='job',
        ),
    ]
