# Generated by Django 4.2.3 on 2023-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_job_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Middle Developer', 'Middle Developer'), ('Senior Developer', 'Senior Developer')], default='Junior Developer', max_length=200),
        ),
    ]
