# Generated by Django 4.2.3 on 2023-07-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_contact_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
